// Package dataplane is the contract napkey-core requires of whatever component
// authenticates proxied traffic and owns the upstream account pool.
//
// napkey-core is the only writer of API keys (DESIGN.md section 4); it pushes them
// to a data plane, and that data plane is what customer traffic actually
// authenticates against. Until this package existed the coupling was direct: the
// concrete kiro-go HTTP client appeared in handler signatures, so the control
// plane could not describe what it needed without naming who provided it.
//
// The interface is what allows a second data plane to be added without touching
// wallet, ledger, pricing, or key-lifecycle code. Billing does not depend on which
// engine served a request, and this package is where that boundary is stated
// rather than implied.
//
// Scope is deliberately narrow: key lifecycle plus one health read. A data plane
// asking for more than this would be taking over decisions that belong to the
// control plane, which is the coupling this package exists to prevent.
package dataplane

import (
	"context"
	"errors"
)

// ErrNotFound means the data plane holds no such resource.
//
// For a delete this is success rather than failure: the goal is that the key no
// longer authenticates, and a key that was never there satisfies it.
var ErrNotFound = errors.New("dataplane: resource not found")

// ErrUnauthorized means the data plane rejected our admin credential.
//
// Startup treats this as fatal on purpose. Every key creation would fail, so
// surfacing it in the deploy log is better than discovering it on the first
// customer who tries to create a key.
var ErrUnauthorized = errors.New("dataplane: admin credential rejected")

// Provider is the set of operations napkey-core needs from a data plane.
type Provider interface {
	// CreateKey registers a key and returns the id the data plane assigned to it.
	//
	// The cleartext is supplied by the caller rather than generated by the data
	// plane: napkey-core stores only a SHA-256 and shows the cleartext exactly once,
	// so it has to be the component that chooses the value. The call is made
	// synchronously while that cleartext is still in memory, because once the
	// response is sent there is nothing left to retry with.
	CreateKey(ctx context.Context, req CreateKeyRequest) (remoteID string, err error)

	// UpdateKey applies an edit to an existing key. Retryable: it needs only the
	// remote id, which is why the background syncer can own it.
	UpdateKey(ctx context.Context, remoteID string, req UpdateKeyRequest) error

	// DeleteKey removes a key. A missing key counts as success; see ErrNotFound.
	DeleteKey(ctx context.Context, remoteID string) error

	// ListKeys reads every key the data plane holds, used to reconcile drift.
	ListKeys(ctx context.Context) ([]KeyView, error)

	// OperationsStatus reports pool and usage-reporting health for the operations
	// dashboard and the public status page.
	OperationsStatus(ctx context.Context) (*OperationsStatus, error)

	// Health reports whether the data plane is reachable and the credential works.
	Health(ctx context.Context) error
}

// The struct tags below are kiro-go's wire shape, kept here so the current adapter
// can marshal these types directly and this stays a behaviour-preserving change.
// An adapter whose wire format differs should translate into these types rather
// than edit the tags, since the tags describe one provider and the types describe
// the contract.

// KeyView is a key as the data plane reports it.
type KeyView struct {
	ID            string  `json:"id"`
	Name          string  `json:"name,omitempty"`
	KeyMasked     string  `json:"keyMasked"`
	Enabled       bool    `json:"enabled"`
	CreatedAt     int64   `json:"createdAt"`
	LastUsedAt    int64   `json:"lastUsedAt,omitempty"`
	RPMLimit      int     `json:"rpmLimit,omitempty"`
	TPMLimit      int     `json:"tpmLimit,omitempty"`
	TokenLimit    int64   `json:"tokenLimit,omitempty"`
	CreditLimit   float64 `json:"creditLimit,omitempty"`
	TokensUsed    int64   `json:"tokensUsed"`
	CreditsUsed   float64 `json:"creditsUsed"`
	RequestsCount int64   `json:"requestsCount"`
}

// CreateKeyRequest is the desired state of a newly provisioned key.
type CreateKeyRequest struct {
	Name        string  `json:"name,omitempty"`
	Key         string  `json:"key"`
	Enabled     *bool   `json:"enabled,omitempty"`
	RPMLimit    int     `json:"rpmLimit,omitempty"`
	TPMLimit    int     `json:"tpmLimit,omitempty"`
	TokenLimit  int64   `json:"tokenLimit,omitempty"`
	CreditLimit float64 `json:"creditLimit,omitempty"`
}

// UpdateKeyRequest is a patch. Nil fields are left untouched by the data plane,
// which is why every field is a pointer: a zero value here means "set to zero",
// not "leave alone", and conflating the two would silently clear a customer's
// limits.
type UpdateKeyRequest struct {
	Name        *string  `json:"name,omitempty"`
	Enabled     *bool    `json:"enabled,omitempty"`
	RPMLimit    *int     `json:"rpmLimit,omitempty"`
	TPMLimit    *int     `json:"tpmLimit,omitempty"`
	TokenLimit  *int64   `json:"tokenLimit,omitempty"`
	CreditLimit *float64 `json:"creditLimit,omitempty"`
}

// UsageReportingStatus is the health of the data plane's usage reporting pipeline.
//
// This matters to billing: usage that is queued or dropped is traffic that was
// served and may never be charged, so the numbers are surfaced rather than
// averaged into a single health flag.
type UsageReportingStatus struct {
	Enabled   int64 `json:"enabled"`
	Healthy   int64 `json:"healthy"`
	Queued    int64 `json:"queued"`
	Sent      int64 `json:"sent"`
	Duplicate int64 `json:"duplicate"`
	Dropped   int64 `json:"dropped"`
	Pending   int64 `json:"pending"`
}

// OperationsStatus is the data plane's own view of its pool and traffic.
type OperationsStatus struct {
	Version         string               `json:"version"`
	Accounts        int                  `json:"accounts"`
	Available       int                  `json:"available"`
	TotalRequests   int64                `json:"totalRequests"`
	SuccessRequests int64                `json:"successRequests"`
	FailedRequests  int64                `json:"failedRequests"`
	RecentRequests  int64                `json:"recentRequests"`
	RecentFailures  int64                `json:"recentFailures"`
	TotalTokens     int64                `json:"totalTokens"`
	Uptime          int64                `json:"uptime"`
	UsageReporting  UsageReportingStatus `json:"usageReporting"`
}
